/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as DietaRouteImport } from './routes/dieta'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as SessaoRouteImport } from './routes/sessao'
import { Route as TreinoRouteImport } from './routes/treino'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as DietaIndexRouteImport } from './routes/dieta.index'
import { Route as DietaMarketRouteImport } from './routes/dieta.market'
import { Route as DietaWeekRouteImport } from './routes/dieta.week'
import { Route as ProgressoIndexRouteImport } from './routes/progresso.index'
import { Route as ProgressoIdRouteImport } from './routes/progresso.$id'
import { Route as ResumoIdRouteImport } from './routes/resumo.$id'
import { Route as RotinaIdRouteImport } from './routes/rotina.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const DietaRoute = DietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const SessaoRoute = SessaoRouteImport.update({
  id: '/sessao',
  path: '/sessao',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoRoute = TreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DietaIndexRoute = DietaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DietaRoute,
} as any)
const DietaMarketRoute = DietaMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => DietaRoute,
} as any)
const DietaWeekRoute = DietaWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => DietaRoute,
} as any)
const ProgressoIndexRoute = ProgressoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgressoRoute,
} as any)
const ProgressoIdRoute = ProgressoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProgressoRoute,
} as any)
const ResumoIdRoute = ResumoIdRouteImport.update({
  id: '/resumo/$id',
  path: '/resumo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RotinaIdRoute = RotinaIdRouteImport.update({
  id: '/rotina/$id',
  path: '/rotina/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/dieta': typeof DietaRouteWithChildren
  '/inicio': typeof InicioRoute
  '/mcp': typeof McpRoute
  '/perfil': typeof PerfilRoute
  '/progresso': typeof ProgressoRouteWithChildren
  '/sessao': typeof SessaoRoute
  '/treino': typeof TreinoRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dieta/market': typeof DietaMarketRoute
  '/dieta/week': typeof DietaWeekRoute
  '/progresso/$id': typeof ProgressoIdRoute
  '/resumo/$id': typeof ResumoIdRoute
  '/rotina/$id': typeof RotinaIdRoute
  '/dieta/': typeof DietaIndexRoute
  '/progresso/': typeof ProgressoIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/inicio': typeof InicioRoute
  '/mcp': typeof McpRoute
  '/perfil': typeof PerfilRoute
  '/sessao': typeof SessaoRoute
  '/treino': typeof TreinoRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dieta/market': typeof DietaMarketRoute
  '/dieta/week': typeof DietaWeekRoute
  '/progresso/$id': typeof ProgressoIdRoute
  '/resumo/$id': typeof ResumoIdRoute
  '/rotina/$id': typeof RotinaIdRoute
  '/dieta': typeof DietaIndexRoute
  '/progresso': typeof ProgressoIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/dieta': typeof DietaRouteWithChildren
  '/inicio': typeof InicioRoute
  '/mcp': typeof McpRoute
  '/perfil': typeof PerfilRoute
  '/progresso': typeof ProgressoRouteWithChildren
  '/sessao': typeof SessaoRoute
  '/treino': typeof TreinoRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dieta/market': typeof DietaMarketRoute
  '/dieta/week': typeof DietaWeekRoute
  '/progresso/$id': typeof ProgressoIdRoute
  '/resumo/$id': typeof ResumoIdRoute
  '/rotina/$id': typeof RotinaIdRoute
  '/dieta/': typeof DietaIndexRoute
  '/progresso/': typeof ProgressoIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/dieta'
    | '/inicio'
    | '/mcp'
    | '/perfil'
    | '/progresso'
    | '/sessao'
    | '/treino'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dieta/market'
    | '/dieta/week'
    | '/progresso/$id'
    | '/resumo/$id'
    | '/rotina/$id'
    | '/dieta/'
    | '/progresso/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/inicio'
    | '/mcp'
    | '/perfil'
    | '/sessao'
    | '/treino'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dieta/market'
    | '/dieta/week'
    | '/progresso/$id'
    | '/resumo/$id'
    | '/rotina/$id'
    | '/dieta'
    | '/progresso'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/dieta'
    | '/inicio'
    | '/mcp'
    | '/perfil'
    | '/progresso'
    | '/sessao'
    | '/treino'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dieta/market'
    | '/dieta/week'
    | '/progresso/$id'
    | '/resumo/$id'
    | '/rotina/$id'
    | '/dieta/'
    | '/progresso/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  DietaRoute: typeof DietaRouteWithChildren
  InicioRoute: typeof InicioRoute
  McpRoute: typeof McpRoute
  PerfilRoute: typeof PerfilRoute
  ProgressoRoute: typeof ProgressoRouteWithChildren
  SessaoRoute: typeof SessaoRoute
  TreinoRoute: typeof TreinoRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ResumoIdRoute: typeof ResumoIdRoute
  RotinaIdRoute: typeof RotinaIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieta': {
      id: '/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof DietaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessao': {
      id: '/sessao'
      path: '/sessao'
      fullPath: '/sessao'
      preLoaderRoute: typeof SessaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino': {
      id: '/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof TreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieta/': {
      id: '/dieta/'
      path: '/'
      fullPath: '/dieta/'
      preLoaderRoute: typeof DietaIndexRouteImport
      parentRoute: typeof DietaRoute
    }
    '/dieta/market': {
      id: '/dieta/market'
      path: '/market'
      fullPath: '/dieta/market'
      preLoaderRoute: typeof DietaMarketRouteImport
      parentRoute: typeof DietaRoute
    }
    '/dieta/week': {
      id: '/dieta/week'
      path: '/week'
      fullPath: '/dieta/week'
      preLoaderRoute: typeof DietaWeekRouteImport
      parentRoute: typeof DietaRoute
    }
    '/progresso/': {
      id: '/progresso/'
      path: '/'
      fullPath: '/progresso/'
      preLoaderRoute: typeof ProgressoIndexRouteImport
      parentRoute: typeof ProgressoRoute
    }
    '/progresso/$id': {
      id: '/progresso/$id'
      path: '/$id'
      fullPath: '/progresso/$id'
      preLoaderRoute: typeof ProgressoIdRouteImport
      parentRoute: typeof ProgressoRoute
    }
    '/resumo/$id': {
      id: '/resumo/$id'
      path: '/resumo/$id'
      fullPath: '/resumo/$id'
      preLoaderRoute: typeof ResumoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotina/$id': {
      id: '/rotina/$id'
      path: '/rotina/$id'
      fullPath: '/rotina/$id'
      preLoaderRoute: typeof RotinaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DietaRouteChildren {
  DietaMarketRoute: typeof DietaMarketRoute
  DietaWeekRoute: typeof DietaWeekRoute
  DietaIndexRoute: typeof DietaIndexRoute
}

const DietaRouteChildren: DietaRouteChildren = {
  DietaMarketRoute: DietaMarketRoute,
  DietaWeekRoute: DietaWeekRoute,
  DietaIndexRoute: DietaIndexRoute,
}

const DietaRouteWithChildren = DietaRoute._addFileChildren(DietaRouteChildren)

interface ProgressoRouteChildren {
  ProgressoIdRoute: typeof ProgressoIdRoute
  ProgressoIndexRoute: typeof ProgressoIndexRoute
}

const ProgressoRouteChildren: ProgressoRouteChildren = {
  ProgressoIdRoute: ProgressoIdRoute,
  ProgressoIndexRoute: ProgressoIndexRoute,
}

const ProgressoRouteWithChildren = ProgressoRoute._addFileChildren(
  ProgressoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  DietaRoute: DietaRouteWithChildren,
  InicioRoute: InicioRoute,
  McpRoute: McpRoute,
  PerfilRoute: PerfilRoute,
  ProgressoRoute: ProgressoRouteWithChildren,
  SessaoRoute: SessaoRoute,
  TreinoRoute: TreinoRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ResumoIdRoute: ResumoIdRoute,
  RotinaIdRoute: RotinaIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
